/*
 * Pirate Weather API
 *
 * Pirate Weather provides an open, free, and documented source of government weather data.
 *
 * The version of the OpenAPI document: 2.6.0
 * Contact: mail@pirateweather.net
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Daily : A block containing day-by-day forecasted conditions for the next 7 days.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Daily {
    /// A summary of the daily forecast.
    #[serde(rename = "summary", skip_serializing_if = "Option::is_none")]
    pub summary: Option<String>,
    /// An icon representing the daily forecast.
    #[serde(rename = "icon", skip_serializing_if = "Option::is_none")]
    pub icon: Option<String>,
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<Vec<models::DailyDataInner>>,
}

impl Daily {
    /// A block containing day-by-day forecasted conditions for the next 7 days.
    pub fn new() -> Daily {
        Daily {
            summary: None,
            icon: None,
            data: None,
        }
    }
}
