/*
 * Pirate Weather API
 *
 * Pirate Weather provides an open, free, and documented source of government weather data.
 *
 * The version of the OpenAPI document: 2.9.0
 * Contact: mail@pirateweather.net
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Flags : A block containing miscellaneous data for the API request.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Flags {
    /// The models used to generate the forecast.
    #[serde(rename = "sources", skip_serializing_if = "Option::is_none")]
    pub sources: Option<Vec<String>>,
    #[serde(rename = "sourceTimes", skip_serializing_if = "Option::is_none")]
    pub source_times: Option<Box<models::FlagsSourceTimes>>,
    /// Distance to the closest DWD MOSMIX station to your location in kilometres or miles depending on the units. If there are no stations for your location this will return -999.
    #[serde(rename = "nearest-station", skip_serializing_if = "Option::is_none")]
    pub nearest_station: Option<f64>,
    /// The units used in the forecasts.
    #[serde(rename = "units", skip_serializing_if = "Option::is_none")]
    pub units: Option<String>,
    /// The version of Pirate Weather used to generate the forecast.
    #[serde(rename = "version", skip_serializing_if = "Option::is_none")]
    pub version: Option<String>,
    #[serde(rename = "sourceIDX", skip_serializing_if = "Option::is_none")]
    pub source_idx: Option<Box<models::FlagsSourceIdx>>,
    /// The time taken to process the request in milliseconds. Only returned when version>1.
    #[serde(rename = "processTime", skip_serializing_if = "Option::is_none")]
    pub process_time: Option<i32>,
    /// The ingest version of Pirate Weather used to generate the forecast. Only returned when version>1.
    #[serde(rename = "ingestVersion", skip_serializing_if = "Option::is_none")]
    pub ingest_version: Option<String>,
    /// The name of the closest city to your location. Only returned when version>1.
    #[serde(rename = "nearestCity", skip_serializing_if = "Option::is_none")]
    pub nearest_city: Option<String>,
    /// The name of the closest country to your location. Only returned when version>1.
    #[serde(rename = "nearestCountry", skip_serializing_if = "Option::is_none")]
    pub nearest_country: Option<String>,
    /// The name of the closest state or province to your location. Only returned when version>1.
    #[serde(rename = "nearestSubNational", skip_serializing_if = "Option::is_none")]
    pub nearest_sub_national: Option<String>,
}

impl Flags {
    /// A block containing miscellaneous data for the API request.
    pub fn new() -> Flags {
        Flags {
            sources: None,
            source_times: None,
            nearest_station: None,
            units: None,
            version: None,
            source_idx: None,
            process_time: None,
            ingest_version: None,
            nearest_city: None,
            nearest_country: None,
            nearest_sub_national: None,
        }
    }
}
