/*
 * Pirate Weather API
 *
 * Pirate Weather provides an open, free, and documented source of government weather data.
 *
 * The version of the OpenAPI document: 2.9.0
 * Contact: mail@pirateweather.net
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FlagsSourceIdxNbm {
    /// The X coordinate for the NBM model.
    #[serde(rename = "x", skip_serializing_if = "Option::is_none")]
    pub x: Option<i32>,
    /// The Y coordinate for the NBM model.
    #[serde(rename = "y", skip_serializing_if = "Option::is_none")]
    pub y: Option<i32>,
    /// The latitude coordinate for the NBM model.
    #[serde(rename = "lat", skip_serializing_if = "Option::is_none")]
    pub lat: Option<f64>,
    /// The longitude coordinate for the NBM model.
    #[serde(rename = "long", skip_serializing_if = "Option::is_none")]
    pub long: Option<f64>,
}

impl FlagsSourceIdxNbm {
    pub fn new() -> FlagsSourceIdxNbm {
        FlagsSourceIdxNbm {
            x: None,
            y: None,
            lat: None,
            long: None,
        }
    }
}
