/*
 * Pirate Weather API
 *
 * Pirate Weather provides an open, free, and documented source of government weather data.
 *
 * The version of the OpenAPI document: 2.9.0
 * Contact: mail@pirateweather.net
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Minutely : A block containing minute-by-minute precipitation intensity for the next 60 minutes.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Minutely {
    /// A summary of the minute-by-minute forecast.
    #[serde(rename = "summary", skip_serializing_if = "Option::is_none")]
    pub summary: Option<String>,
    /// An icon representing the minute-by-minute forecast.
    #[serde(rename = "icon", skip_serializing_if = "Option::is_none")]
    pub icon: Option<String>,
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<Vec<models::MinutelyDataInner>>,
}

impl Minutely {
    /// A block containing minute-by-minute precipitation intensity for the next 60 minutes.
    pub fn new() -> Minutely {
        Minutely {
            summary: None,
            icon: None,
            data: None,
        }
    }
}
